services:
  botdownloader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: botdownloader
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - HOME_DIR=/app/data
      - UID=1000
      - GID=1000
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - downloaderbot_net

volumes:
  data:
    name: bot_downloader_persistence
    driver: "local"

networks:
  downloaderbot_net:
    name: downloaderbot_net
    driver: bridge