[project]
name = "downloader-bot"
version = "0.2.0"
description = "A simple telegram bot for use YT-DLP"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.1",
    "python-telegram-bot>=22.7",
    "yt-dlp>=2026.3.17",
]

[dependency-groups]
dev = [
    "bumpver>=2025.1131",
    "imageio>=2.37.3",
    "mypy>=2.0.0",
    "nuitka>=4.1",
    "pillow>=12.2.0",
    "pystray>=0.19.5",
    "pytest>=9.0.3",
]
